version: "3"

services:
  gateway:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./gateway:/gateway
    command: /bin/sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    environment:
      - SECRET_KEY=FAKESECRETKEY
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_URL=postgres://postgres@localhost:5432/crisp-url?password=postgres
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ORIGIN_WHITELIST="http://test.com,https://test.com"
      - SHORT_URL_LENGTH=8
      - REDIRECT_URL=http://localhost:8000
    depends_on:
      - database

  database:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=crisp-url
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
