version: "3"

services:
  database:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=eyelet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  gateway:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./gateway:/gateway
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:8080"
    environment:
      - DJANGO_SETTINGS_MODULES=gateway.settings
      - DEBUG=1
    depends_on:
      - database