version: "3"

services:
  database:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=eyelet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  gateway:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./gateway:/gateway
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:8080"
    environment:
      - SECRET_KEY=FAKESECRETKEY
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_URL=postgres://postgres@localhost:5432/eyelet?password=postgres
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ORIGIN_WHITELIST="http://test.com,https://test.com"
    depends_on:
      - database