# Generated by Django 3.1.12 on 2022-03-20 15:45

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShorter',
            fields=[
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_last_changed', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=255)),
                ('short_url', models.URLField(max_length=255)),
                ('short_url_alias', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_url_suffix', message='Short URL suffix can only contain lowercase alphabets, Uppercase alphabets and numbers', regex='^[a-zA-Z0-9]{8}$')])),
                ('hits', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-dt_created', '-dt_last_changed'],
                'abstract': False,
            },
        ),
    ]
